global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
   - job_name: 'node_exporter'
     static_configs:
       - targets: 
          - '127.0.0.1:9100'
   - job_name: 'beacon-1'
     metrics_path: /metrics    
     static_configs:
       - targets: 
          - '127.0.0.1:5054'
          - '127.0.0.1:5055'          
   - job_name: 'validators-1'
     metrics_path: /metrics
     static_configs:
       - targets: 
          - '127.0.0.1:5064'
          - '127.0.0.1:5065'
   - job_name: 'geth'
     scrape_interval: 15s
     scrape_timeout: 10s
     metrics_path: /debug/metrics/prometheus
     scheme: http
     static_configs:
       - targets: 
          - '127.0.0.1:6060'
          - '127.0.0.1:6061'
         labels:
            chain: engram-tokio