{
 "title": "Erigon",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "quantile",
    "query": "0.0,0.25,0.5, 0.9, 0.97, 0.99, 1"
   },
   { "name": "instance", "label": "instance", "query": { "query": "go_goroutines" } },
   {
    "name": "rate_interval",
    "label": "Rate Interval",
    "query": "1m,10m,30m,1h,3h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Blockchain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Chain head",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sync{instance=~\"$instance\",stage=\"headers\"}",
     "legendFormat": "header: {{instance}}"
    },
    {
     "expr": "chain_head_block{instance=~\"$instance\"}",
     "legendFormat": "block: {{instance}}"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "txpool_pending{instance=~\"$instance\"}",
     "legendFormat": "executable: {{instance}}"
    },
    {
     "expr": "txpool_basefee{instance=~\"$instance\"}",
     "legendFormat": "basefee: {{instance}}"
    },
    {
     "expr": "txpool_queued{instance=~\"$instance\"}",
     "legendFormat": "gapped: {{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_system_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "system: {{instance}}"
    },
    {
     "expr": "increase(process_cpu_seconds_user_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "iowait: {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Use",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "current: {{ instance }}"
    }
   ]
  },
  {
   "title": "Sync Stages progress",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 10, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sync{instance=~\"$instance\"}",
     "legendFormat": "{{ stage }}: {{instance}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "p2p_peers{instance=~\"$instance\"}",
     "legendFormat": "peers: {{instance}}"
    },
    {
     "expr": "rate(p2p_dials{instance=~\"$instance\"}[1m])",
     "legendFormat": "dials: {{instance}}"
    },
    {
     "expr": "rate(p2p_serves{instance=~\"$instance\"}[1m])",
     "legendFormat": "serves: {{instance}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(p2p_ingress{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "ingress: {{instance}}"
    }
   ]
  },
  {
   "title": "Disk bytes/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_io_storage_read_bytes_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "read: {{instance}}"
    },
    {
     "expr": "rate(process_io_storage_written_bytes_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "write: {{instance}}"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "db_size{instance=~\"$instance\"}",
     "legendFormat": "size: {{instance}}"
    },
    {
     "expr": "db_mi_last_pgno{instance=~\"$instance\"}",
     "legendFormat": "db_mi_last_pgno: {{instance}}"
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(rpc_duration_seconds_count{instance=~\"$instance\",success=\"success\"}[1m])",
     "legendFormat": "success {{ method }} {{ instance }} "
    },
    {
     "expr": "rate(rpc_duration_seconds_count{instance=~\"$instance\",success=\"failure\"}[1m])",
     "legendFormat": "failure {{ method }} {{ instance }} "
    }
   ]
  },
  {
   "title": "Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rpc_duration_seconds{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": " {{ method }} {{ instance }} {{ success }}"
    }
   ]
  },
  {
   "title": "Cache keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cache_keys_total{name=\"rpc\",instance=~\"$instance\"}",
     "legendFormat": "keys: {{ instance }} "
    },
    {
     "expr": "cache_list_total{name=\"rpc\",instance=~\"$instance\"}",
     "legendFormat": "list: {{ instance }} "
    },
    {
     "expr": "cache_code_keys_total{name=\"rpc\",instance=~\"$instance\"}",
     "legendFormat": "code_keys: {{ instance }} "
    },
    {
     "expr": "cache_code_list_total{name=\"rpc\",instance=~\"$instance\"}",
     "legendFormat": "code_list: {{ instance }} "
    }
   ]
  },
  {
   "title": "Cache hit-rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 40 },
   "targets": [
    {
     "expr": "sum(delta(cache_total{result=\"hit\",name=\"rpc\",instance=~\"$instance\"}[1m]))/sum(delta(cache_total{name=\"rpc\",instance=~\"$instance\"}[1m])) ",
     "legendFormat": "hit rate: {{ instance }} "
    },
    {
     "expr": "sum(delta(cache_code_total{result=\"hit\",name=\"rpc\",instance=~\"$instance\"}[1m]))/sum(delta(cache_code_total{name=\"rpc\",instance=~\"$instance\"}[1m])) ",
     "legendFormat": "code hit rate: {{ instance }} "
    }
   ]
  },
  {
   "title": "Private api",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "gRPC call, error rates ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (grpc_service, grpc_method, instance) (rate(grpc_server_started_total{instance=~\"$instance\"}[1m]))",
       "legendFormat": "Calls: {{grpc_service}}.{{grpc_method}}, {{instance}}"
      },
      {
       "expr": "sum by (grpc_service, grpc_method, instance) (rate(grpc_server_handled_total{instance=~\"$instance\",grpc_code!=\"OK\"}[1m])) ",
       "legendFormat": "Errors: {{grpc_service}}.{{grpc_method}}, {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}